name: Automação da base de dados

on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 0 * * *'


jobs:
  Pipeline:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v6

      - name: Instalar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Instalar Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1

      - name: Instalar pacotes Python
        run: poetry install --no-root

      - name: Atualizar base de dados
        run: poetry run python etl.py

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Atualização automática de dados
